function  ColorParticle(X0, Index)

    [~,dim] = size(X0);

    Title = sprintf('Particle index = %i', Index);
   
    p = figure;
   
    hold on
    if     dim == 1
    
            scatter(X0(:), zeros(length(X0), 1),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0 0.4470 0.7410] ); 

            scatter(X0(Index), zeros(length(X0), 1),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0.8500 0.3250 0.0980]  ); 
    
    elseif dim == 2
        
            scatter(X0(:,1),X0(:,2),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0 0.4470 0.7410] ); 

            scatter(X0(Index,1),X0(Index,2),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0.8500 0.3250 0.0980]  ); 
    
    elseif dim == 3
    
            scatter3(X0(:,1),X0(:,2),X0(:,3),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0 0.4470 0.7410] ); 

            scatter3(X0(Index,1),X0(Index,2),X0(Index,3),125,'filled', ...
             'MarkerFaceAlpha',7/8, 'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0.8500 0.3250 0.0980]  ); 

    end
    
    hold off 

    set(gca, ...
    'Box'         , 'off'     , ...
    'XMinorTick'  , 'off'      , ...
    'XTick'       , []      , ...
    'YMinorTick'  , 'off'      , ...
    'YTick'       , []      , ...
    'ZTick'       , []      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...    
    'ZGrid'       , 'off'      , ... 
    'XColor'      , 'none', ...
    'ZColor'      , 'none', ...
    'YColor'      , 'none' );
    
    axis equal  
    
    % Add labels
    hTitle = title(Title);
    hXLabel = xlabel('x');
    hYLabel = ylabel('y');
    
    % Adjust font
    set(gca, 'FontName', 'Georgia')
    set([hTitle, hXLabel, hYLabel], 'FontName', 'Georgia')
    set([hXLabel, hYLabel], 'FontSize', 10)     
    set(hTitle, 'FontSize', 12, 'FontWeight' , 'bold','Color','#010206')
    
    set(gcf, 'InvertHardCopy','off')    


end
